service: Routeme
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: ${opt:stage}
  versionFunctions: false

custom:
  ACCOUNT_ID: !Ref AWS::AccountId
  REGION: !Ref AWS::Region
  STAGE: ${self:provider.stage}
  APPLICATION: 'videoblur'

resources:
  Resources:
    functions:
      FacedetectionStartFunction:
        name: ${self:custom.STAGE}-Admin-FacedetectionStartFunction
        runtime: nodejs18.x
        handler: './controllers/start_detection.handler'
        role: 'arn:aws:iam::021891572638:role/masterrole'
        package:
          patterns:
            - 'controllers/start_detection.js'
            - 'package.json'
        events:
          - http:
              path: '/admin/start-detection'
              method: 'get'
              cors: true
functions:
  FacedetectionStartFunction:
    name: ${self:custom.STAGE}-Admin-FacedetectionStartFunction
    runtime: nodejs18.x
    handler: './controllers/start_detection.handler'
    role: 'arn:aws:iam::021891572638:role/masterrole'
    package:
      patterns:
        - 'controllers/start_detection.js'
        - 'package.json'
    events:
      - http:
          path: '/admin/start-detection'
          method: 'get'
          cors: true
