name: devenv
channels:
  - conda-forge  # Channel to source packages from
dependencies:
  - python=3.9  # Specify Python version
  - opencv  
  - pip
  - ffmpeg
  - pip:
      - boto3
      - moviepy
      - requests
      - tqdm
