name: Deployment Workflow

on:
  push:
    branches:
      - dev

jobs:
  deploy_development:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev' 
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Install Serverless Framework
        run: npm install -g serverless@3.38.0

      - name: Echo Serverless Version
        run: |
          sls_version=$(sls -v)
          echo "Serverless Framework Version: $sls_version"

      - name: Install dependencies
        run: |
          npm install

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
        run: |
          serverless config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY -o
          sls deploy --stage dev